version: '3'

networks:
  default:
    name: apps_shared
    external: true

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    # needed to properly mount the volume below
    user: root
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./prom-data/:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.listen-address=:9091'
      - '--storage.tsdb.retention.time=60d'
    ports:
      - "9091:9091/tcp"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    user: root
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini

  # speedtest-exporter:
  #   image: miguelndecarvalho/speedtest-exporter
  #   container_name: speedtest-exporter
  #   environment: []
  #     # - SPEEDTEST_PORT=<speedtest-port> #optional
  #     # - SPEEDTEST_SERVER=<server-id> #optional
  #   ports:
  #     - 9798:9798
  #   restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100/tcp"

  docker-stats-exporter:
    image: wywywywy/docker_stats_exporter
    container_name: docker-stats-exporter
    ports:
      - 9487:9487
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
