global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9091"]
      labels:
        machine: optiplex

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]
      labels:
        machine: optiplex

  # - job_name: "speed_test"
  #   scrape_interval: 4h
  #   scrape_timeout: 2m
  #   static_configs:
  #   - targets: ["speedtest-exporter:9798"]

  - job_name: "docker-stats"
    static_configs:
    - targets: ["docker-stats-exporter:9487"]
      labels:
        machine: optiplex

  - job_name: 'pihole'

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job="node"}'
        - '{job="docker-stats"}'

    static_configs:
    - targets: ["192.168.0.101:9091"]
      labels:
        machine: pihole

