version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/etc/letsencrypt/live/mckjns.com/fullchain.pem:/etc/ssl/fullchain.pem"
      - "/etc/letsencrypt/live/mckjns.com/privkey.pem:/etc/ssl/privkey.pem"
    restart: unless-stopped
      
networks:
  default:
    name: apps_shared
    external: true
