version: '3.3'

networks:
  default:
    name: apps_shared
    external: true

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 3002:3001  # <Host Port>:<Container Port>
    restart: always
