version: "3"

networks:
  default:
    name: apps_shared
    external: true

services:
  server:
    container_name: spotify-server
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8070:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://spotify.api.mckjns.com # This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: https://spotify.mckjns.com
      SPOTIFY_PUBLIC: <redacted>
      SPOTIFY_SECRET: <redacted>
  mongo:
    container_name: spotify-mongo
    image: mongo:4.4.8
    volumes:
      - ./your_spotify_db:/data/db

  web:
    container_name: spotify-web-ui
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3010:3000"
    environment:
      API_ENDPOINT: https://spotify.api.mckjns.com
