version: "3.7"

networks:
  default:
    name: apps_shared
    external: true

volumes:
  redis_data:
  notused:
    driver: local

services:
  excalidraw-server:
    container_name: excalidraw
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_APP_BACKEND_V2_GET_URL: ${VITE_APP_BACKEND_V2_GET_URL}
        VITE_APP_BACKEND_V2_POST_URL: ${VITE_APP_BACKEND_V2_POST_URL}
        VITE_APP_WS_SERVER_URL: ${VITE_APP_WS_SERVER_URL}
    restart: always
    # ports:
    #   - "3001:80"
    environment:
      NODE_ENV: production
      TZ: Europe/Amsterdam
      PUB_SRV_NAME: ${PUB_SRV_NAME}
      PUB_SRV_NAME_WS: ${PUB_SRV_NAME_WS}
      VITE_APP_BACKEND_V2_GET_URL: ${VITE_APP_BACKEND_V2_GET_URL}
      VITE_APP_BACKEND_V2_POST_URL: ${VITE_APP_BACKEND_V2_POST_URL}
      VITE_APP_WS_SERVER_URL: ${VITE_APP_WS_SERVER_URL}
    volumes:
      - notused:/opt/node_app/app/node_modules
  excalidraw-room:
    container_name: excalidraw-room
    image: excalidraw/excalidraw-room:latest
    restart: always
    environment:
      TZ: Europe/Amsterdam
      PORT: 3002
    # ports:
    #   - "3002:3002"
  excalidraw-storage-backend:
    container_name: excalidraw-storage
    stdin_open: true
    build:
      context: https://github.com/kitsteam/excalidraw-storage-backend.git#v0.1.2
      target: production
    # ports:
      # - "3003:8080"
    environment:
      STORAGE_URI: redis://:${REDIS_PASSWORD}@excalidraw-redis:6379
      STORAGE_TTL: 2592000000

  redis:
    container_name: excalidraw-redis
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
